### ISSUE TITLE
Missing narrow-unicode Python 2.7 wheels

### ISSUE THREAD

**Issue by henryiii** [pandas-dev/pandas#27056]
On PyPI, narrow-unicode wheels are not provided. This causes [my](https://github.com/scikit-hep/decaylanguage) Azure pipelines that uses Pandas to take 8 minutes on the Python 2.7 versions instead of 45 seconds for all other Python 3 versions. The manylinux container does [have both](https://github.com/pypa/manylinux) "cp27mu" and "cp27m" versions - and Azure is using the narrow-unicode one. Numpy does provide this narrow-unicode wheel, so it's only Pandas doing the build.

Could narrow unicode builds be provided as well? It would be a file like `*cp27-cp27m-manylinux1_x86_64.whl` in addition to `cp27-cp27mu-manylinux1_x86_64.whl `.

**Comment by TomAugspurger** [comment]
This is at https://github.com/MacPython/pandas-wheels. We had entries for 

```
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
    - os: linux
      env:
        - MB_PYTHON_VERSION=2.7
        - PLAT=i686
```

Though, FYI, we've dropped 2.7 support on master.
