### ISSUE TITLE
ENH: PyPy3 testing

### ISSUE THREAD

**Issue by jcpunk** [pandas-dev/pandas#37653]
#### Is your feature request related to a problem?

With the increasing support for PyPy3 in NumPy, it would be helpful if pandas started testing against PyPy3.

#### Describe the solution you'd like

Please consider adding `pypy3` to the `.travis.yml` (allowed to fail for now).

#### API breaking implications

No expected API breaks

#### Describe alternatives you've considered

This is more of a portability concern than anything else.

#### Additional context

Something like:

```yaml
  matrix:
   -  python: pypy3
      env:
        - JOB="pypy3" PATTERN="(not slow and not network and not clipboard)"
  allow_failures:
   -  python: pypy3
      env:
        - JOB="pypy3" PATTERN="(not slow and not network and not clipboard)"
```
