### ISSUE TITLE
CI: use conda incubator in doc build

### ISSUE THREAD

**Issue by fangchenli** [pandas-dev/pandas#39175]
#39043 enabled conda incubator for the benchmark build. But I didn't get the doc build to work. I had something like this

```yml
web_and_docs:
    name: Web and docs
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l -e {0}

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Cache conda
      uses: actions/cache@v2
      with:
        path: ~/conda_pkgs_dir
        key: ${{ runner.os }}-conda-${{ hashFiles('${{ env.ENV_FILE }}') }}

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: pandas-dev
        channel-priority: strict
        environment-file: ${{ env.ENV_FILE }}
        use-only-tar-bz2: true

    - name: Environment Detail
      run: |
        conda info
        conda list

    - name: Build Pandas
      run: |
        python setup.py build_ext -j 2
        python -m pip install -e . --no-build-isolation --no-use-pep517

    - name: Build website
      run: python web/pandas_web.py web/pandas --target-path=web/build

    - name: Build documentation
      run: doc/make.py --warnings-are-errors | tee sphinx.log ; exit ${PIPESTATUS[0]}

    # This can be removed when the ipython directive fails when there are errors,
    # including the `tee sphinx.log` in te previous step (https://github.com/ipython/ipython/issues/11547)
    - name: Check ipython directive errors
      run: "! grep -B10 \"^<<<-------------------------------------------------------------------------$\" sphinx.log"

......
```

There are no errors in the output of `doc/make.py --warnings-are-errors`, but it exits with code 1. Also, using multiple workers to build the doc doesn't improve the performance.
