### ISSUE TITLE
STYLE Investigate restructuredtext_lint as pre-commit hook

### ISSUE THREAD

**Issue by MarcoGorelli** [pandas-dev/pandas#41986]
pytest have such a hook to check rst files https://github.com/pytest-dev/pytest/blob/main/.pre-commit-config.yaml :

```yaml
    -   id: rst
        name: rst
        entry: rst-lint --encoding utf-8
        files: ^(RELEASING.rst|README.rst|TIDELIFT.rst)$
        language: python
        additional_dependencies: [pygments, restructuredtext_lint]
```

Would this be worth including in pandas? Investigations would be welcome
